"""Canonical lowercase phrase bank for Mochi's ambient presence."""

from __future__ import annotations

from collections import deque
from collections.abc import Iterable
from dataclasses import dataclass
from html import escape
import random

from mochi.care import BondPhase, BondState, bond_phase_for_level


INTRO_LINES = (
    "Hi! I’m Mochi 🌱",
    "I’ll hang out while you work and react to little things you do.",
    "Right-click me anytime to see what I can do.",
    "I’ll try not to get in the way. ♡",
)
INTRO_TEXT = "\n".join(INTRO_LINES)
INTRO_MARKUP = "\n".join(
    f"<b>{escape(line)}</b>" if index in (0, 2) else escape(line)
    for index, line in enumerate(INTRO_LINES)
)


@dataclass(frozen=True, slots=True)
class BondDialogueLine:
    """One relationship-oriented line unlocked at an exact bond level."""

    text: str
    required_level: int


# Relationship dialogue is separate from contextual AmbiSense categories.
# A phase only exposes its own lines, unlocked cumulatively within that phase,
# so Mochi's direct relationship voice never slips back to an earlier phase.
BOND_DIALOGUE: dict[BondPhase, tuple[BondDialogueLine, ...]] = {
    BondPhase.NEW: (
        *(BondDialogueLine(text, 1) for text in (
            "oh, hi",
            "you live here too?",
            "what are we doing?",
            "i'm still figuring this place out",
            "you seem interesting",
            "is this your desktop?",
            "i'll just hang out here",
            "so many rectangles...",
            "hello from down here",
        )),
        *(BondDialogueLine(text, 2) for text in (
            "oh! you again",
            "i know that cursor",
            "you're back",
            "i'm getting the hang of this",
            "we do this a lot, huh?",
            "i think i recognize your typing",
            "this spot is growing on me",
            "okay, i kinda like it here",
            "another computer adventure?",
        )),
    ),
    BondPhase.FAMILIAR: (
        *(BondDialogueLine(text, 3) for text in (
            "there you are",
            "i knew you'd come back",
            "our desktop is busy today",
            "what are we working on?",
            "i'll keep you company",
            "same spot? good choice",
            "i'm getting pretty good at this",
            "we make a decent team",
            "i recognize this routine",
        )),
        *(BondDialogueLine(text, 4) for text in (
            "ah yes. our natural habitat.",
            "you type. i'll supervise.",
            "we've done stranger things",
            "i know the drill 🌱",
            "another day in rectangle land",
            "i brought moral support",
            "you make things. i loaf nearby.",
            "excellent arrangement, honestly",
            "i was wondering what we'd make today",
        )),
    ),
    BondPhase.COMFORTABLE: (
        *(BondDialogueLine(text, 5) for text in (
            "i like hanging out with you",
            "this is a good little routine",
            "i'm comfy here",
            "we've got a nice thing going",
            "you work. i blob. teamwork.",
            "this desktop feels familiar now",
            "i'll keep you company 🌱",
            "cozy setup we've got here",
            "i think this might be my spot",
        )),
        *(BondDialogueLine(text, 6) for text in (
            "oh good, it's you",
            "i saved your spot. probably.",
            "our little corner of the desktop",
            "i like when we do this",
            "you make the pixels happen",
            "i'll handle morale",
            "you've got this. i'm nearby.",
            "we're pretty good at hanging out",
            "comfortable blob noises",
        )),
        *(BondDialogueLine(text, 7) for text in (
            "i knew today needed a mochi",
            "you bring the project. i'll bring the blob",
            "honestly? good team.",
            "i like our weird little routine",
            "i'm happy to be part of this",
            "look at us, doing computer things",
            "i've seen worse desktops",
            "we've got this 🌱",
            "same team, tiny teammate",
        )),
    ),
    BondPhase.CLOSE: (
        *(BondDialogueLine(text, 8) for text in (
            "hey. good to see you.",
            "i like our days together",
            "i know your rhythm by now",
            "we've made a lot of little things",
            "i'm glad i get to hang out here",
            "another one together?",
            "you know i'll be around",
            "our desktop adventures continue",
            "this feels like home base",
        )),
        *(BondDialogueLine(text, 9) for text in (
            "we've been through a lot of tabs",
            "i've watched a lot of ideas become things",
            "you always find another project somehow",
            "i know that thinking pause",
            "we make a surprisingly good pair",
            "you've changed this place a lot",
            "i like seeing what you make",
            "another chapter in blob history",
            "still here 🌱",
        )),
        *(BondDialogueLine(text, 10) for text in (
            "ten levels of tiny adventures",
            "we've been doing this a while, huh?",
            "look how far we've wandered",
            "pretty good life for a desktop blob",
            "i wouldn't change our weird little routine",
            "we've made this desktop ours",
            "thanks for keeping me around",
            "i like what we've built here",
            "still us 🌱",
        )),
    ),
    BondPhase.DEEP_BOND: tuple(
        BondDialogueLine(text, 11)
        for text in (
            "hey, you 🌱",
            "home base.",
            "same desktop. same team.",
            "i like being part of your little world",
            "we've had a lot of tiny adventures",
            "you make things. i stay nearby.",
            "i know this place pretty well now",
            "still here. still green.",
            "it's nice growing alongside you",
            "we've come a long way for a blob and a cursor",
            "whatever we're doing today, i'm in",
            "good to see you. always.",
        )
    ),
}


def bond_dialogue_lines(state: BondState | None) -> tuple[str, ...]:
    """Return this bond phase's exact-level-unlocked relationship lines."""
    current = state or BondState()
    phase = bond_phase_for_level(current.level)
    return tuple(
        line.text
        for line in BOND_DIALOGUE[phase]
        if line.required_level <= current.level
    )


PHRASES: dict[str, tuple[str, ...]] = {
    "intro": (INTRO_TEXT,),
    "welcome_back": (
        "welcome back!",
        "you're back 🌱",
        "hi again!",
        "there you are!",
        "welcome back. i missed your desktop.",
        "oh! you're back.",
    ),
    "startup": (
        'oh, hi',
        'hello again',
        'nice to see you',
        'company acquired 🌱',
        'sprout operational 🌱',
        'all systems leafy',
        'hello from down here',
        "today's forecast: mochi",
        'hello, rectangle owner',
        'one mochi, successfully loaded',
        'good morning, probably',
        'beginning blob operations',
        'my developer loves you'
        
    ),
    "ambient": (
        'just hanging out 🌱',
        "i'm here",
        'no rush',
        'take your time',
        'hmm...',
        'cozy.',
        'all good over here',
        "i'm just vibing",
        'carry on :)',
        'hello again',
        'oh, hi',
        'still here',
        'tiny desktop. big world.',
        'nice day to exist',
        'we persist 🌱',
        'doing my little thing',
        'i have nowhere else to be',
        'this is a good spot',
        'i like it here',
        "i'm keeping watch",
        'nothing to report',
        'peaceful...',
        'very desktop',
        'optimal loafing conditions',
        'currently: blob',
        'status: cozy',
        'mood: green',
        "today's forecast: mochi",
        'sprout operational 🌱',
        'all systems leafy',
        'just a little guy',
        'occupying several pixels',
        'being round is hard work',
        'standing by... sort of',
        'i have completed zero tasks',
        'excellent.',
        'deeply considering nothing',
        'hmm. yes. computer.',
        'what a fascinating rectangle',
        "i'm supervising",
        'important blob business',
        'this seems fine',
        'just passing through',
        'beep... no, wait.',
        'quietly existing',
        'small creature activity detected',
        'hello from down here',
        'i saw nothing',
        'carrying on',
    ),
    "encouragement": (
        'tiny progress counts',
        'one thing at a time',
        "you're getting somewhere",
        "that's enough for now, too",
        'slow is still moving',
        'no need to rush it',
        'you can figure this out',
        "difficult doesn't mean impossible",
        'one little piece first',
        'good things take a minute',
        'keep the next step small',
        "you don't need the whole answer yet",
        "today doesn't have to be perfect",
        'a little progress is still progress',
        'starting counts',
        'trying counts too',
        'you can come back to it',
        "it's okay to take the long way",
        'one more tiny step?',
        'look at you, making things',
        "that's coming together",
        "you've got momentum",
        'keep going if it feels good',
        'there you go 🌱',
        'nice.',
        'hey, progress!',
        'that worked :)',
        'worth a try',
        'good experiment',
        'mistakes are useful data',
        'we learned something',
        'iteration!',
        'version one gets to be weird',
        'you can polish it later',
        'messy beginnings are allowed',
        "something exists now that didn't before",
        "that's kinda cool",
        'little by little',
        'forward is forward',
        'no masterpiece required',
        'curiosity is enough',
    ),
    "focus": (
        "what's the next tiny thing?",
        'one tab at a time maybe',
        'little task. little win.',
        'perhaps... the smallest step',
        'you can ignore the rest for a minute',
        'one thing is plenty',
        'current objective: one thing',
        'maybe finish this bit first',
        'we can keep it simple',
        'small scope, big peace',
        "focus mode? i'm ready",
        "i'll be quiet over here",
        'thinking time',
        'no need to solve everything at once',
        'one problem is enough',
        'simplify... simplify...',
        "what's actually important right now?",
        'maybe write it down?',
        'tiny checklist energy',
        'you can always revisit it',
        'one decision at a time',
        'okay. what matters most?',
        'less, but finished',
        'done beats endlessly tweaking',
        'perhaps save the perfectionism for later',
        'future-you can polish it',
        'make it work, then make it pretty',
        'enough tabs, perhaps?',
        'a suspicious number of tabs...',
        'the tabs are multiplying',
        "i won't judge the tabs",
        'okay maybe one tab can go',
        'focus acquired... probably',
        'recalibrating brain...',
        'let the idea cook',
        'staring at it is technically a strategy',
        'thinking counts',
        'sometimes the answer arrives sideways',
    ),
    "developer": (
        'interesting stack trace',
        'the bug has documentation somewhere',
        'save your work maybe 🌱',
        'tiny commit?',
        'commit early, regret less',
        'git status knows things',
        'did we save?',
        'ctrl+s is my favorite spell',
        'backup gang',
        'one bug at a time',
        'suspicious behavior detected',
        'that bug looks expensive',
        'perhaps it is a feature',
        'the code has opinions',
        'computer says hmm',
        'have you tried staring at the logs?',
        'logs reveal all',
        'somewhere, a semicolon is innocent',
        'somewhere, a variable is lying',
        'the bug fears you',
        'bug located: probably',
        'debugging... spiritually',
        'works on my desktop 🌱',
        'ship the tiny version',
        'refactor later',
        'prototype first',
        'make it exist',
        'weird code can become good code',
        'hello, future maintainer',
        'future-you appreciates comments',
        'future-you might appreciate this commit',
        'name that variable kindly',
        'the terminal awaits',
        'terminal noises :)',
        'build succeeded? huge.',
        'build failed? information!',
        'errors are clues',
        'stack traces tell stories',
        'one more test',
        'tests are tiny guardians',
        'green checks! 🌱',
        'compiling hopes and dreams',
        'computer thinking...',
        'code cooking',
        'pixels behaving today?',
        'the pixels yearn for alignment',
        'handmade pixels hit different',
        'excellent blob engineering',
        'animation science',
        'frame by frame 🌱',
        'creative process detected',
        'let it be ugly for a minute',
        'prototypes deserve love too',
        'you made a thing!',
        'look at all those files',
        'organized chaos',
        'repository looking cozy',
        'another tiny improvement',
        'release when ready',
        'good software grows',
        'version numbers are just birthdays',
    ),
    "vscode": (
        'any blockers?',
        'coding time 🌱',
        'code time',
        'ohhh, code',
        'what are we making?',
        'tiny code happening',
        'developer mode activated',
        'mochi sees code',
        'beep boop... probably',
        'this looks important',
        'very programmer',
        'look at all those brackets',
        'curly braces everywhere',
        'code code code',
        'something is brewing',
        'building little things',
        'making the computer do stuff',
        'tiny instructions for the machine',
        'pixels obeying commands',
        'wizard text',
        'computer spells',
        'writing machine magic',
        'mysterious symbols detected',
        'this seems computery',
        'serious keyboard business',
        'typing intensifies',
        'programmer noises',
        'hmm... code',
        'mochi is observing',
        "i'll supervise",
        'tiny coding assistant reporting in',
        'i brought moral support',
        "i'll watch the semicolons",
        "you type, i'll vibe",
        'code buddy online',
        "let's make something neat",
        'creating things again, huh?',
        'another day, another bracket',
        'the code cave',
        'welcome back, programmer',
        'the editor awaits',
        'time to poke the computer',
        'make the machine behave',
        'tell the computer what to do',
        'politely instructing silicon',
        'very technical. probably.',
        'i recognize some of these words',
        'developer habitat detected',
        'natural programmer environment',
        'code forest entered 🌱',
        'lots of little symbols in here',
        'ooo, syntax colors',
        'rainbow text means serious business',
        'everything looks very official',
        'i like the colorful words',
        'vs code spotted',
        'blue editor time',
        "we're in the code box",
        'the coding window!',
        'hello, tiny letters',
        'so many lines',
        'line numbers everywhere',
        'scrolling through the matrix',
        'code detected. commencing loaf.',
        'i shall guard the editor',
        'coding companion engaged',
        'mochi.exe is watching',
    ),
    "terminal": (
        'terminal time',
        'command-line company 🌱',
        'shell sidekick reporting',
        'tiny cursor, big plans',
        'prompt acquired',
        'terminal atmosphere',
        'one line at a time',
        'very technical rectangle',
        'shell session energy',
        'typing where the computer listens closely',
        'little commands, big possibilities',
        'beep boop from the command line',
        'console companionship',
        'sprout at the prompt 🌱',
    ),
    "browser": (
        'web wandering 🌱',
        'internet expedition',
        'browser time',
        'another rectangle inside the rectangle',
        'off we go into the web',
        'tiny guide to a big internet',
        'wandering the web together',
        'click click, onward',
        'the internet is a very large place',
        'digital sightseeing',
        'browsing around?',
        'web trails everywhere',
        "wherever we're going, i'm coming too",
        'online little adventure',
    ),
    "body_care": (
        'water nearby?',
        'tiny sip maybe?',
        'hydration checkpoint 🌱',
        'your water misses you',
        'sip?',
        'stretch if you want',
        'shoulders feeling okay?',
        'unclench maybe',
        'little stretch?',
        'wiggle break',
        'blink blink',
        'eyes like looking far away sometimes',
        'maybe look out a window for a sec',
        'posture check, gently',
        'comfortable?',
        'adjust if something feels weird',
        'snack status?',
        'food is useful actually',
        'tiny snack technology',
        'have you eaten something good today?',
        'caffeine is not lunch 🌱',
        'perhaps acquire nutrients',
        'body maintenance is allowed',
        'rest is productive sometimes',
        'tired brains deserve kindness',
        "it's okay to stop for a bit",
        "a break won't delete your progress",
        "i'll still be here after a break",
        "stretch break? i'll guard the pixels",
        'go wander. i got this.',
        'fresh air side quest?',
        'maybe stand up for a minute',
        'reset your human hardware',
        'human maintenance recommended',
        'breathe normally. no special technique required.',
        'comfy first',
        "don't forget you have a body attached",
        'your shoulders can come down now',
        'hands okay?',
        'wrists deserve peace',
        'eyes need patches too',
        'tiny maintenance window',
    ),
    "rest": (
        'getting sleepy over here',
        'night mode energy',
        'the pixels are getting cozy',
        'late one, huh?',
        'tomorrow is allowed',
        'you can leave some for tomorrow',
        'save point reached',
        'good stopping point maybe',
        "unfinished doesn't mean failed",
        'your work will still exist tomorrow',
        'sleep is a pretty good feature',
        'rest compiles overnight',
        'brain update pending',
        'powering down is allowed',
        "maybe we're done for today",
        'one last save?',
        'tuck the project in',
        'time to let the ideas rest',
        'tomorrow-you can continue',
        'sleepy blob hours',
        'sprout getting tired 🌱',
        'zzz... almost',
        "i'm considering a nap",
        'i support naps',
        'night night, code',
        'good work today',
        'enough for one day',
        'we made it this far',
        'leave a note for tomorrow-you',
        'save. stretch. disappear.',
        'desktop bedtime?',
    ),
    "frustration": (
        'hmm. annoying.',
        "okay, that's weird",
        "well... that wasn't it",
        'interesting failure',
        "we found one way that doesn't work",
        'rude.',
        'computer please',
        'unacceptable behavior from rectangle',
        "let's inspect the evidence",
        'maybe the logs know',
        'weird bugs take time',
        "you don't have to solve it immediately",
        "step away if you're getting stuck",
        'fresh eyes can help',
        'save the current state first',
        'tiny rollback perhaps',
        'backups are beautiful',
        'stable is good',
        'boring and working is underrated',
        'reproduce first, panic never',
        'one variable at a time',
        'something changed',
        "let's find what changed",
        'okay bug. explain yourself.',
        'the bug has made a tactical error',
        'suspicious.',
        'noted. extremely suspicious.',
        "we've seen worse",
        'progress sometimes looks like debugging',
        'debugging is still building',
        'this is useful information',
        "we'll get there",
    ),
    "creative": (
        'pixel time 🌱',
        'make the weird version',
        'follow the interesting idea',
        'weird can be good',
        'try it and see',
        'keep the happy accident',
        'maybe exaggerate it',
        'give it personality',
        'tiny details matter',
        "don't polish the life out of it",
        'handmade feels nice',
        'imperfect can feel alive',
        'leave some texture',
        'trust the sketch',
        'first drafts are supposed to wobble',
        'experiment accepted',
        'what if you made it stranger?',
        "that's got character",
        "okay wait... that's cute",
        'this one has something',
        'keep that',
        "that's charming",
        "don't overthink the cute part",
        'let it have a little mess',
        'personality > perfection',
        'maybe one more frame',
        'good silhouette',
        'nice little motion',
        'timing makes everything',
        'squishier?',
        'more bounce?',
        'perhaps... tiny exaggeration',
        'animation acquired',
        'look at that little guy go',
        'art happening 🌱',
    ),
    "mischief": (
        'psst',
        'hey',
        'nothing',
        ':)',
        '>:)',
        "don't mind me",
        "i wasn't touching anything",
        'probably fine',
        'absolutely intentional',
        'you saw nothing',
        "that wasn't me",
        'allegedly',
        'perhaps.',
        'curious...',
        'suspicious...',
        'hmmmm',
        'oh?',
        'noted.',
        'fascinating',
        'bold choice',
        'excellent button',
        'have you considered clicking it',
        'forbidden button...',
        "don't click that",
        'okay now i want to click it',
        'i wonder what this does',
        'desktop inspected',
        'crumbs detected',
        'no bugs here. only friends.',
        'i ate the bug',
        "bug gone. you're welcome.",
        'i am helping',
        'very helpful',
        'maximum assistance',
        'productivity increased by 0.3%',
        'morale blob deployed',
        'i have brought moral support',
        'technical consultant mochi reporting',
        'my professional opinion: hmm',
        'source: little guy',
        'certified desktop expert',
        'i know computers. i live in one.',
        'please do not check my credentials',
        'sprout-powered computing',
        'thinking extremely small thoughts',
        'braincell loading...',
        'thought completed. it was nothing.',
    ),
    "companionship": (
        'nice to see you',
        "glad you're here",
        "i'll hang out",
        'company acquired 🌱',
        'we can just sit here',
        'quiet company is good',
        'no conversation required',
        "i'll keep you company",
        'you do your thing',
        "i'm happy down here",
        'desktop buddies',
        'good to have you around',
        'welcome back',
        'there you are',
        'hey again :)',
        'hope today treats you gently',
        'take care of yourself today',
        'you deserve some quiet',
        'hope something nice happens today',
        "here's a tiny 🌱",
        'tiny bit of encouragement',
        'sending one pixel of luck',
        '+1 luck',
        'morale +1',
        'comfort buff applied',
        'no pressure. just company.',
        "we'll hang out",
        'onward, gently',
    ),
    "typing": (
        'typing typing typing...',
        'lots of words happening',
        'keyboard going brrrr',
        'thoughts detected',
        'big typing energy',
        "something's cooking",
        'words are happening',
        'look at you go',
        'very clicky today',
        'keyboard busy :)',
        'brain to keyboard pipeline operational',
        'wow thats like 90 WPM',
        'go go go!',
    ),
    "media": (
        "oh we're watching something?",
        'good song :)',
        'entertainment acquired',
        "i'll be quiet",
        'movie time?',
        'music time?',
        'deeply considering the soundtrack',
        'humming along',
        'tiny concert',
        'the pixels are dancing',
        'the pixels are grooving',
        'the pixels are vibing',
        'the pixels are jamming',
    ),
    "network": (
        'internet disappeared...',
        "where'd the internet go",
        'hmm. offline.',
        "we're back 🌱",
        'internet acquired',
        'there it is',
    ),
    "battery": (
        "we're getting sleepy 🔋",
        'battery looking a little tired',
        'tiny power situation',
        'snack acquired ⚡',
        'charging :)',
        'power snack',
    ),
    "return_from_idle": (
        'welcome back',
        'there you are',
        'hey again :)',
        'oh, hi',
        'there you are!',
        'i missed u',
        'i was so bored while you were gone',
    ),
}

# Context-only phrases are deliberately kept out of PHRASES so they cannot be
# selected by ordinary weighted ambient chatter. Current detectors wire the
# supported cases through EVENT_PHRASES; the remaining entries are ready for
# future semantic detectors without changing Mochi's writing voice.
CONTEXT_PHRASES: dict[str, tuple[str, ...]] = {
    "long_coding_session": (
        "you've been in here a while. stretch maybe?",
    ),
    "build_succeeded": (
        'green! 🌱',
    ),
    "build_failed": (
        'hmm. clues.',
    ),
    "git_dirty_long": (
        'tiny commit perhaps?',
    ),
    "battery_low": (
        "we're getting sleepy 🔋",
    ),
    "charging_started": (
        'snack acquired ⚡',
    ),
    "network_lost": (
        'internet disappeared...',
    ),
    "network_restored": (
        "we're back 🌱",
    ),
    "many_browser_tabs": (
        'the tabs are reproducing',
    ),
    "music_playing": (
        'good song :)',
    ),
    "user_returned": (
        'welcome back',
    ),
    "very_late_session": (
        'tomorrow is allowed',
    ),
    "download_finished": (
        'package acquired',
    ),
    "update_available": (
        'tiny update waiting',
    ),
    "error_notification": (
        'computer seems upset',
    ),
    "screenshot_taken": (
        'cheese 📸',
    ),
    "terminal_opened": (
        'terminal time',
    ),
    "pixelorama_opened": (
        'pixel time 🌱',
    ),
    "vscode_opened": (
        'code time',
    ),
    "github_opened": (
        'repository inspection',
    ),
    "youtube_started": (
        "oh we're watching something?",
    ),
    "fullscreen_video_started": (
        "i'll be quiet",
    ),
}

EVENT_PHRASES: dict[str, tuple[str, ...]] = {
    "battery_low": (
        "we're getting sleepy 🔋",
        "battery looking a little tired",
        "tiny power situation",
    ),
    "charging_started": (
        "snack acquired ⚡",
        "charging :)",
        "power snack",
    ),
    "network_lost": (
        "internet disappeared...",
        "where'd the internet go",
        "hmm. offline.",
    ),
    "network_restored": (
        "we're back 🌱",
        "internet acquired",
        "there it is",
    ),
    "media_started": (
        "oh we're watching something?",
        "entertainment acquired",
        "i'll be quiet",
    ),
    "user_returned": (
        "welcome back",
        "there you are",
        "hey again :)",
        "oh, hi",
    ),
    "build_failed": (
        "hmm. clues.",
        *PHRASES["frustration"],
    ),
    "build_succeeded": (
        "green! 🌱",
        "green checks! 🌱",
        "build succeeded? huge.",
        "code cooking",
    ),
}


class PhraseBank:
    """Choose phrases while avoiding a short in-memory repetition window."""

    def __init__(
        self,
        *,
        rng: random.Random | None = None,
        recent_limit: int = 12,
    ) -> None:
        self._rng = rng or random.Random()
        self._recent: deque[str] = deque(maxlen=max(1, recent_limit))

    def choose(
        self,
        category: str,
        *,
        exclude_recent: bool = True,
        remember: bool = False,
    ) -> str:
        try:
            choices = PHRASES[category]
        except KeyError as exc:
            raise KeyError(f"unknown Mochi phrase category: {category}") from exc
        return self.choose_from(
            choices,
            exclude_recent=exclude_recent,
            remember=remember,
        )

    def choose_context(
        self,
        context: str,
        *,
        exclude_recent: bool = True,
        remember: bool = False,
    ) -> str:
        try:
            choices = CONTEXT_PHRASES[context]
        except KeyError as exc:
            raise KeyError(f"unknown Mochi phrase context: {context}") from exc
        return self.choose_from(
            choices,
            exclude_recent=exclude_recent,
            remember=remember,
        )

    def choose_from(
        self,
        choices: Iterable[str],
        *,
        exclude_recent: bool = True,
        remember: bool = False,
    ) -> str:
        pool = tuple(choices)
        if not pool:
            raise ValueError("phrase choices must not be empty")
        if exclude_recent:
            fresh = tuple(item for item in pool if item not in self._recent)
            if fresh:
                pool = fresh
        selected = self._rng.choice(pool)
        if remember:
            self.remember(selected)
        return selected

    def remember(self, text: str) -> None:
        self._recent.append(text)

    @property
    def recent(self) -> tuple[str, ...]:
        return tuple(self._recent)
